# Generated by Django 5.1.2 on 2024-11-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.TextField(default=None, null=True, unique=True),
        ),
    ]
