# Generated by Django 5.1.2 on 2024-11-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
