# Generated by Django 5.1.2 on 2024-10-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_author_email_alter_author_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repost',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
