# Generated by Django 5.1.2 on 2024-11-23 22:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
