# Generated by Django 5.1.1 on 2024-10-11 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_post_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
