# Generated by Django 5.1.2 on 2024-11-18 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_alter_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='user_approval_required',
            field=models.BooleanField(default=False),
        ),
    ]
