# Generated by Django 5.1.2 on 2024-10-29 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_repost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(),
        ),
    ]
