# Generated by Django 5.1.2 on 2024-11-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_alter_author_github_alter_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default_profile.jpg', null=True, upload_to='images/profilePictures'),
        ),
    ]
