# Generated by Django 4.2.11 on 2024-10-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_alter_author_friends_alter_post_image_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
