# Generated by Django 5.1.2 on 2024-11-23 22:52

from django.db import migrations
import uuid

def populate_uuid(apps, schema_editor):
    Author = apps.get_model('yourapp', 'Author')
    for author in Author.objects.all():
        if not author.uuid:
            author.uuid = uuid.uuid4()
            author.save()

class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_author_uuid_alter_author_id'),
    ]

    operations = [
    ]
