# Generated by Django 5.1.2 on 2024-11-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_author_groups_author_is_superuser_author_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/profilePictures'),
        ),
    ]
