# Generated by Django 5.1.1 on 2024-10-11 22:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='commentlike',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='postlike',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
