# Generated by Django 5.1.2 on 2024-11-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_alter_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
