# Generated by Django 5.1.1 on 2024-10-11 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_remove_post_author_commentlike_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='node.author'),
        ),
    ]
