# Generated by Django 5.1.2 on 2024-11-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_alter_author_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default_profile.jpg', max_length=500, null=True, upload_to='images/profilePictures'),
        ),
    ]
