# Generated by Django 5.1.2 on 2024-11-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
