# Generated by Django 5.1.1 on 2024-10-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_post_visibility_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS'), ('DELETED', 'DELETED'), ('UNLISTED', 'UNLISTED')], default='PUBLIC', max_length=50),
        ),
    ]
