# Generated by Django 5.1.2 on 2024-11-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_alter_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, default='', max_length=500, null=True, upload_to='images/profilePictures'),
        ),
    ]
