# Generated by Django 5.1.2 on 2024-11-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0008_alter_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contentType',
            field=models.CharField(default='text/plain', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='images/postImages'),
        ),
    ]
