# Generated by Django 5.1.2 on 2024-11-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0004_alter_post_published'),
        ('node', '0009_post_contenttype_alter_post_image_content'),
    ]

    operations = [
    ]
