# Generated by Django 5.1.2 on 2024-11-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0009_alter_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
