# Generated by Django 5.1.2 on 2024-11-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_merge_20241103_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
