# Generated by Django 5.1.1 on 2024-10-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_author_email_author_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.TextField(choices=[('PUBLIC', 'PUBLIC'), ('FRIENDS', 'FRIENDS'), ('DELETED', 'DELETED'), ('UNLISTED', 'UNLISTED')], default='PUBLIC', max_length=50),
        ),
    ]
