# Generated by Django 5.1.2 on 2024-10-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_author_email_author_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.URLField()),
                ('following', models.URLField()),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
