# Generated by Django 5.1.2 on 2024-11-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_alter_author_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, default=False, null=True, upload_to='images/postImages'),
        ),
    ]
