# Generated by Django 5.1.1 on 2024-10-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_alter_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.TextField(default='PUBLIC', max_length=50),
        ),
    ]
