# Generated by Django 5.1.2 on 2024-10-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='github',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='page',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
