# Generated by Django 5.1.2 on 2024-11-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_alter_post_image_content_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, default='', max_length=100000, null=True, upload_to='images/profilePictures'),
        ),
    ]
