# Generated by Django 5.1.2 on 2024-11-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_alter_post_image_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.ImageField(blank=True, null=True, upload_to='images/postImages'),
        ),
    ]
