# Generated by Django 5.1.2 on 2024-11-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_alter_author_display_name'),
        ('node', '0012_alter_post_image_content'),
    ]

    operations = [
    ]
