# Generated by Django 5.1.1 on 2024-10-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0012_alter_post_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='id',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='id',
        ),
        migrations.AlterField(
            model_name='commentlike',
            name='object_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='object_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
