# Generated by Django 5.1.2 on 2024-11-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0013_alter_author_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, max_length=1000, null=True, upload_to='images/profilePictures'),
        ),
    ]
