# Generated by Django 5.1.1 on 2024-10-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0013_remove_commentlike_id_remove_postlike_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='liker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='node.author'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='liker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='node.author'),
        ),
    ]
