# Generated by Django 4.2.11 on 2024-10-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0012_alter_author_description_alter_author_github_and_more'),
        ('node', '0013_remove_commentlike_id_remove_postlike_id_and_more'),
    ]

    operations = [
    ]
