# Generated by Django 5.1.1 on 2024-10-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0014_commentlike_liker_postlike_liker'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
