# Generated by Django 4.2.11 on 2024-10-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0014_merge_20241016_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.CharField(max_length=200),
        ),
    ]
