# Generated by Django 5.1.2 on 2024-11-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0015_allowednode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotenode',
            name='password',
            field=models.CharField(help_text='Password for authentication', max_length=128),
        ),
    ]
