# Generated by Django 5.1.1 on 2024-10-16 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0012_alter_author_description_alter_author_github_and_more'),
        ('node', '0015_comment_published'),
    ]

    operations = [
    ]
