# Generated by Django 5.1.2 on 2024-11-16 04:19


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0016_alter_remotenode_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_approval_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
            },
        ),
        migrations.AlterField(
            model_name='author',
            name='display_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, default='http://darkgoldenrod/api', max_length=50, null=True),
        ),
    ]
