# Generated by Django 5.1.2 on 2024-10-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0015_alter_follow_follower_alter_follow_following'),
        ('node', '0016_merge_20241016_0634'),
    ]

    operations = [
    ]
