# Generated by Django 5.1.1 on 2024-10-17 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_image'),
        ('node', '0017_merge_20241016_2103'),
        ('node', '0017_merge_20241016_2341'),
    ]

    operations = [
    ]
