# Generated by Django 5.1.2 on 2024-10-16 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_merge_20241016_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repost', models.BooleanField(default=False)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='node.post')),
            ],
        ),
    ]
