# Generated by Django 5.1.2 on 2024-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_sitesetting_alter_author_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
