# Generated by Django 5.1.2 on 2024-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_sitesetting_alter_author_display_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorIDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
