# Generated by Django 5.1.2 on 2024-10-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_image'),
        ('node', '0017_merge_20241016_2103'),
        ('node', '0017_merge_20241016_2341'),
        ('node', '0017_merge_20241016_2349'),
    ]

    operations = [
    ]
