# Generated by Django 5.1.1 on 2024-10-17 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0018_merge_0011_image_0017_merge_20241016_2103'),
        ('node', '0018_merge_20241017_0007'),
    ]

    operations = [
    ]
