# Generated by Django 5.1.1 on 2024-10-20 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0017_merge_20241016_2341'),
        ('node', '0017_merge_20241016_2349'),
        ('node', '0018_merge_0011_image_0017_merge_20241016_2103'),
    ]

    operations = [
    ]
