# Generated by Django 5.1.2 on 2024-11-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0018_authoridcounter_alter_author_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorIDCounter',
        ),
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
