# Generated by Django 5.1.2 on 2024-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0018_alter_post_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
