# Generated by Django 5.1.2 on 2024-11-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0019_delete_authoridcounter_author_url_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.CharField(blank=True, default='http://darkgoldenrod/api/', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
