# Generated by Django 5.1.1 on 2024-10-18 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0018_share'),
        ('node', '0019_merge_20241017_0101'),
    ]

    operations = [
    ]
