# Generated by Django 5.1.2 on 2024-11-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0019_alter_post_text_content'),
        ('node', '0020_alter_author_host_alter_author_url'),
    ]

    operations = [
    ]
