# Generated by Django 5.1.2 on 2024-10-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0020_merge_0018_share_0019_merge_20241017_0101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Share',
        ),
    ]
