# Generated by Django 5.1.1 on 2024-10-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0020_merge_0018_share_0019_merge_20241017_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/profilePictures'),
        ),
        migrations.DeleteModel(
            name='Share',
        ),
    ]
