# Generated by Django 5.1.2 on 2024-10-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0021_delete_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends'), ('UNLISTED', 'Unlisted'), ('DELETED', 'Deleted')], default='PUBLIC', max_length=50),
        ),
    ]
