# Generated by Django 5.1.2 on 2024-10-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0021_post_content_type_alter_author_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='post',
            name='image_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
