# Generated by Django 5.1.2 on 2024-10-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0021_alter_author_password_alter_author_profile_image_and_more'),
        ('node', '0022_alter_post_visibility'),
    ]

    operations = [
    ]
